name: Handle GPML changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pathways/**/*.gpml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # inspired by https://dev.to/scienta/get-changed-files-in-github-actions-1p36
  changed-gpmls:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      added-modified: ${{ steps.changes.outputs.added-modified }}
      copied: ${{ steps.changes.outputs.copied }}
      deleted: ${{ steps.changes.outputs.deleted }}
      renamed: ${{ steps.changes.outputs.renamed }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "GPML files were changed in pull request ${{ github.event.before }} -> ${{ github.event.after }}"
          
          echo "::set-output name=added-modified::$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'added or modified:'
            git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi
          
          echo "::set-output name=copied::$(git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'copied:'
            git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi

          echo "::set-output name=deleted::$(git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'deleted:'
            git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi
            
          echo "::set-output name=renamed::$(git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'renamed:'
            git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi
          
  metadata:
    runs-on: ubuntu-latest
    needs: changed-gpmls
    # only run if gpmls were added or modified
    if: ${{needs.changed-gpmls.outputs.added-modified}}
    steps:
      - name: Checkout homologyConverterActions repo
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Install deps
        run: |
          wget https://github.com/wikipathways/meta-data-action/releases/download/v0.0.1/meta-data-action-0.0.1-jar-with-dependencies.jar

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/
          key: ${{ runner.os }}-java-${{ hashFiles('meta-data-action-0.0.1-jar-with-dependencies.jar') }}
          restore-keys: |
            ${{ runner.os }}-java-
            
      - name: Generate info and datanode files
        run: |
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating info and datanode files for $wpid ($f)"
            # TODO: Is the following correct? Is the authentication key correct?
            java -jar meta-data-action-0.0.1-jar-with-dependencies.jar hbasaric/homologyConverterActions pathways/"$wpid"/"$wpid".gpml $(date --utc +%F)
          done
          
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/WP*/WP*.{json,tsv}
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update metadata files'
              git push
          fi
          
  pubmed:
    runs-on: ubuntu-20.04
    needs: [changed-gpmls, metadata]
    # only run if gpmls were added or modified
    if: ${{needs.changed-gpmls.outputs.added-modified}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - working-directory: scripts/generate-references
        run: |
          npm install
          node index.js

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/*/*-bibliography.tsv
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update formatted references'
              git push
          fi
          
  frontmatter:
    runs-on: ubuntu-20.04
    needs: [changed-gpmls, metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install SSH Client ??
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install deps
        run: |
          pip install python-frontmatter
          
      - name: Create pathway frontmatter
        run: |        
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating frontmatter file for $wpid"
            json_info_f=./pathways/"$wpid"/"$wpid"-info.json
            old_info_f=./pathways/"$wpid"/"$wpid".info
            if [ -e "$json_info_f" ]; then
              python scripts/create_pathway_frontmatter.py "$json_info_f"
            elif [ -e "$old_info_f" ]; then
              python scripts/create_pathway_frontmatter.py "$old_info_f"
            else
              echo "info file missing for $wpid" >2
            fi
          done

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/*/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update frontmatter .md files'
              git push
          fi

  json-svg:
    needs: [changed-gpmls]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homologyConverterActions repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        working-directory: scripts/generate-svgs
        run: |
          npm install
          sudo apt-get install -y xmlstarlet
            
      - name: Convert GPML to JSON and SVG
        working-directory: scripts/generate-svgs
        run: |
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating JSON and SVG files for $wpid"
            
            for old_f in ../../pathways/"$wpid"/"$wpid".{json,svg}; do 
              if [ -e "$old_f" ]; then
                rm "$old_f"
              fi
            done
            
            ./gpmlconverter --id "$wpid" ../../pathways/"$wpid"/"$wpid".gpml ../../pathways/"$wpid"/"$wpid".svg
            
            # delete intermediate JSON files
            rm ../../pathways/"$wpid"/"$wpid".json.b4bridgedb.json
            rm ../../pathways/"$wpid"/"$wpid".b4wd.json
            rm ../../pathways/"$wpid"/"$wpid".b4hgnc.json
            
            # pretty print the JSON
            for json_f in ../../pathways/"$wpid"/"$wpid".json; do
              mv "$json_f" "$json_f".tmp.json 
              jq -S . "$json_f".tmp.json >"$json_f"
              rm "$json_f".tmp.json
            done
          done

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/WP*/WP*.{json,svg}
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update JSON and SVG files'
              git push
          fi
          
  sync-site-repo-added-modified:
    runs-on: ubuntu-latest
    needs: [changed-gpmls, metadata, pubmed, frontmatter]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: homologyConverterActions
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client ??
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cp homologyConverterActions/pathways/*/*.md wikipathways.github.io/_pathways/
          cp homologyConverterActions/pathways/*/*-bibliography.tsv wikipathways.github.io/_data/
          # Disabling WPx-datanodes.tsv until this issue is closed:
          # https://github.com/wikipathways/meta-data-action/issues/1
          #cp wikipathways-database/pathways/*/*-datanodes.tsv wikipathways.github.io/_data/
          cd wikipathways.github.io
          git add _pathways/*.md
          git add _data/*.tsv
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update tsv and md files'
              git push
          fi
          
  sync-site-repo-deleted:
    runs-on: ubuntu-latest
    needs: changed-gpmls
    # only run if gpmls were deleted
    if: ${{needs.changed-gpmls.outputs.deleted}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: homologyConverterActions
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client ??
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cd wikipathways.github.io
          for f in ${{needs.changed-gpmls.outputs.deleted}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "deleting $wpid from wikipathways.github.io"
            if [ -e _pathways/"$wpid".md ]; then
              git rm _pathways/"$wpid".md
            fi
            if [ -e _data/"$wpid"-bibliography.tsv ]; then
              git rm _data/"$wpid"-bibliography.tsv
            fi
            if [ -e _data/"$wpid"-datanodes.tsv ]; then
              git rm _data/"$wpid"-datanodes.tsv
            fi
          done          
          git add _pathways/*.md
          git add _data/*.tsv
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git pull
              git commit -m 'Remove deleted tsv and md file(s)'
              git push
          fi